### ISSUE TITLE
Search bar issue

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#1]
**Description**: 
When user search incorrect/invalid data in search bar then there is no message "No data found".

**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2.Enter invalid data in search bar of home screen

**Expected behaviour:**
 When user search invalid data in search bar there must be a message "No Data Found".

**Reference video URL**: 
https://drive.google.com/file/d/1ho-oyoT9RxG0ZfnZxMO6Okos3OVnCAMr/view?usp=sharing

**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Functional

**Comment by solkennedy** [comment]
This should be fixed with a UI update, but not with this release

**Comment by MrGurmeet** [comment]
Retesting:
Description: Error message appear when user try to invalid search
Attachment: https://drive.google.com/file/d/144Tul28ImKfdtpyxoej1YYU12d0Pixy_/view?usp=sharing
