### ISSUE TITLE
Send test Notifications

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#10]
**Description**: 
When user tap on send notification then date & time is visible which is invalid.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to settings
3. tap on Send test notifications.
**Expected behaviour:**
Set the feature according to the title/Set the tile according to the feature
**Reference video URL**: 
https://drive.google.com/file/d/1Ml6tosXlrbaQcjpuxw3ejgjc1l5Enbbx/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
As designed for beta only

**Comment by MrGurmeet** [comment]
Okay
