### ISSUE TITLE
Back to setup flow(& logout)

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#11]
**Description**: 
When user tap on "Back to setup flow(& logout) then account automatically logout without any popup.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to settings
3. tap on Back to setup flow(& logout)
**Expected behaviour:**
Add confirmation popup when user tap on Back to setup flow(& logout).
**Reference video URL**: 
https://drive.google.com/file/d/12vqfBgCVyM28DsRU4047DAiqkya8_GPP/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
Beta behavior only, as designed

**Comment by MrGurmeet** [comment]
ok
