### ISSUE TITLE
Settings/Professional team

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#12]
**Description**: 
It saves the invalid data in email field which is invalid. Apply proper validations on all email  fields  of Professional team.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to settings
3. Tap on Coparent support team
4. Enter invalid data in email fields 
5. Go back
**Expected behaviour:**
Email field must accept valid email with @gmail.com format
**Reference video URL**: 
https://drive.google.com/file/d/1DASmGzWtadq69xGx_LCXXV8RIhIGLnJk/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
fixed in build 82

**Comment by MrGurmeet** [comment]
Retesting:
Note: As, i retest again in build 95 email field is still accepting invalid data.
URL: https://drive.google.com/file/d/1sZOGsWD1LA2If9MmOX1GKJTk8XgVhmu5/view?usp=sharing
