### ISSUE TITLE
App notifications

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#14]
**Description**: 
When user tap on text the toggles in app notifications are on/off which is invalid.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to settings
3. Tap on App notifications
4. tap on text and see all toggles 
**Expected behaviour:**
Toggle must be opened only when user tap on toggle button.
*Reference video URL**: 
https://drive.google.com/file/d/1C8QxGRGQTlGCoWzU7U_4j553KED-UNfj/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
Fixed in build 83
