### ISSUE TITLE
Settings/personal profile professional team

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#15]
**Description**: 
When user Go to personal profile and professional team and then come back without entering anything saved message is showing which is invalid.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to settings
3. Go to personal profile & professional team and come back
**Expected behaviour:**
Add "Save" button in personal profile and professional team and saved popup appear only  when user tap on save button not appear while tapping on back button.
*Reference video URL**: 
https://drive.google.com/file/d/1ENbYSfmOB-gO397Nai2DnmVzxDrg6Haa/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
Fixed build 83
