### ISSUE TITLE
Coach

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#16]
**Description**: 
The user is confused about the Date which is not visible correctly. It must be in DD/MM/YYYY Format.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to Coach
**Expected behaviour:**
Date must be in DD/MM/YYYY Format.
*Reference video URL**: 
https://drive.google.com/file/d/14S2OFn2d6rr_J_hAFN3lm3cXp8q2-EL-/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
Fair enough - we are only targeting US customers right now so it will be ok to them
