### ISSUE TITLE
Settings/family profile

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#17]
**Description**: 
In family profile, When Child's name is not written and user tap on add button then Cross sign is visible which is invalid.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to Family profile
3. tap on Add button
**Expected behaviour:**
There must be message please enter Child's name first.
*Reference video URL**: 
https://drive.google.com/file/d/15aSsA9t3fBgUj_jKJL8u3NWG7NfwvcTq/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
Fixed in build 82
