### ISSUE TITLE
Settings/Family profile

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#19]
**Description**: 
In family profile, When user tap on other/none the blank area appear. and user is able to pronouns without child's name.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Go to Family profile
3. Tap on pronouns and select others/none
4. Add pronouns without child's name
**Expected behaviour:**
When user  select pronouns Others/none then it must be appear User is able to add pronouns if child's name is selected.
*Reference video URL**: 
https://drive.google.com/file/d/1Yld3brpVpgCTnhvWgJ2VQo5xsGccrJWK/view?usp=sharing
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66
**Issue Type:** Functionality

**Comment by solkennedy** [comment]
Fixed in build 82
