### ISSUE TITLE
Message bar

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#3]
**Description**: 
When user press arrow button in search bar then error message appear but after entering data in message bar the error message is not disappearing which is invalid.

**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2.Press arrow button of the send button and see error

**Expected behaviour:**
When user enter data in search bar after seeing error message then error message must be disappeared because user is entering the data.
**Reference video URL**: 
https://drive.google.com/file/d/1vmNH3KtUa48zosjgDZeUPmHtYdBkqdK6/view?usp=sharing

**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Functional

**Comment by solkennedy** [comment]
Fixed in build 83

**Comment by MrGurmeet** [comment]
Retesting
**Note**: This issue is successfully fixed in build 83.
