### ISSUE TITLE
Journal report

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#30]
**Description**: 
The title and content are appearing very closely to each other
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Tap journal
3. add journal and download PDF and see downloaded PDF

**Expected behaviour:**
The title should be at the middle of the PDF report
*Reference video URL**: 
https://prnt.sc/LvQCMzXVS40t
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 133

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
As designed
