### ISSUE TITLE
manage subscription

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#31]
**Description**: 
The first letter of best is in lowercase which is invalid.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Tap on manage subscription
3. tap on free trial and see annual unlimited plan
**Expected behaviour:**
Change first letter of the "best" to uppercase "Best"
*Reference video URL**: 
https://drive.google.com/file/d/1ySHe9YRkn7dGhzVYnANhryTcAvP2T6fn/view?usp=sharing
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 133

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
As designed
