### ISSUE TITLE
Manage subscription

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#32]
**Description**: 
When user tap on Subscribed then app center is opening which is invalid
**To Reproduce** 

Steps to Reproduce the behaviour:
1.Open the App
2. Tap on manage subscription
3. Purchase any plan and tap on subscribed and see
**Expected behaviour:**
Only plan details should be open while tapping on subscribed plan
*Reference video URL**: 
https://drive.google.com/file/d/12OmfKogRsEcXDyK5AurGQO7K-U0mgd2T/view?usp=sharing
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 133

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
Behavior is governed by app store
