### ISSUE TITLE
Personal Profile

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#4]
**Description**: 
First name and last name both fields are accepting numerical values which is invalid.

**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2.Go to profile
3.Enter digits in first name and last name

**Expected behaviour:**
First name and last name both fields should accept only alphabets otherwise it shows error.

**Reference video URL**: 
https://drive.google.com/file/d/1vBNsRZP7eewzDakRZGwkkm9g83bqII9n/view?usp=sharing

**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]

**Issue Type:** Functional

**Comment by solkennedy** [comment]
Fixed in build 77

**Comment by MrGurmeet** [comment]
Retesting
**Note**: This issue is successfully fixed in build build 87.
