### ISSUE TITLE
Personal profile/support team

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#6]
**Description**: 
When user is trying to change their phone number and contact support team then phone number is not added but message is submitting which is invalid.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2.Go to profile
3. Tap on support team
4. tap on submit button without entering any phone number

**Expected behaviour:**
Error message must appear "please enter your number" when user tap on submit button 
**Reference video URL**: 
https://drive.google.com/file/d/1wkAZNeYGD6Ka3cZ6KeBMYqunDkD76TaM/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]
Build number: 66

**Issue Type:** Functional

**Comment by solkennedy** [comment]
Won't fix in this release

**Comment by MrGurmeet** [comment]
Retesting:
Description: Error message appear when user try to submit without any data.
Attachment: https://drive.google.com/file/d/1kkFshG059wYcy8sCcunQlxFKHzK00NLV/view?usp=sharing
