### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#7]
**Description**: 
When enter long first name in profile section then on home page the first name is going outside of the screen which is invalid

**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2.Enter long first name
3.See homescreen

**Expected behaviour:**
The first name on the home screen must be appear attractive to user without going outside of the screen.

**Reference video URL**: 
https://drive.google.com/file/d/1MmZBV59V4v9jTHzwVMN7orVDo-dNn-Z1/view?usp=sharing

**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]

**Issue Type:** UI/UX

**Comment by solkennedy** [comment]
Fixed in build 78

**Comment by MrGurmeet** [comment]
Retesting:
**Note**: This issue is successfully fixed in build 87.
