### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#8]
**Description**: 
When user is trying to enter the mobile number while sign in then placeholder is not clearly visible to user.
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Enter phone number.

**Expected behaviour:**
Placeholder must be visible clearly to user when user start typing the phone number.
**Reference video URL**: 
https://drive.google.com/file/d/1iBK1I1c77krUtN65quPA291iCea3CAoL/view?usp=sharing

**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
Fixed in build 79

**Comment by MrGurmeet** [comment]
Retesting:
**Note:** This issue is successfully fixed in build 87.
