### ISSUE TITLE
Sign in screen

### ISSUE THREAD

**Issue by MrGurmeet** [bestinterest/tracker#9]
**Description**: 
User is able to slide the sign in screen left and right side and able to see clearly blank screen which is invalid
**To Reproduce**
Steps to Reproduce the behaviour:
1.Open the App
2. Slide the screen left and right
**Expected behaviour:**
Screen must be fixed. User only slide the images on slider.
**Reference video URL**: 
https://drive.google.com/file/d/12xLltxLHeDs3cdm6gl-xFciB86VysRb1/view?usp=sharing
**Device Details:** 
Device: [iPhone]
OS: [iOS11]
iOS version:[17.5.1]

**Issue Type:** Improvement

**Comment by solkennedy** [comment]
This is a built-in flutterflow widget - cannot be fixed.

**Comment by MrGurmeet** [comment]
Ok
